### ISSUE TITLE
The camera entity does not support requesting width and height

### ISSUE THREAD

**Issue by Enzokot** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#168]
After updating HomeAssistant to 2021.09.0 I am getting warnings in the log:
`2021-09-04 12:28:13 WARNING (MainThread) [homeassistant.components.camera] The camera entity camera.roborock_vacuum_map does not support requesting width and height, please open an issue with the integration author`
May be this help [chapter `Custom integrations: Cameras`](https://www.home-assistant.io/blog/2021/09/01/release-20219/#breaking-changes)

**Comment by Bellavista** [comment]
Same for me, The camera entity camera.mappa_cerchio does not support requesting width and height, please open an issue with the integration author. i installed only now the addon. Homeassitant 2021.9.4

**Comment by Bellavista** [comment]
Hi, Piotr
toghether the first message i recive a long list of 'camera_thumbnail' has been deprecate.... can help you for analisis
thanks

2021-09-12 22:27:20 WARNING (MainThread) [homeassistant.components.camera] The camera entity camera.mappa_rufus does not support requesting width and height, please open an issue with the integration author
2021-09-12 22:27:20 WARNING (MainThread) [homeassistant.components.camera] The websocket command 'camera_thumbnail' has been deprecated
2021-09-12 22:27:20 WARNING (MainThread) [homeassistant.components.camera] The websocket command 'camera_thumbnail' has been deprecated
2021-09-12 22:27:20 WARNING (MainThread) [homeassistant.components.camera] The websocket command 'camera_thumbnail' has been deprecated

**Comment by PiotrMachowski** [comment]
@Bellavista this is not a problem with this integration, but with a lovelace map card ([related issue](https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/issues/67))

**Comment by rainman369** [comment]
I am having the same issues, which are also mentioned in several other open issues. The map seems to work and the vacuum works, but I am constantly getting the following log errors:

1. Entity camera.xiaomi_cloud_map_extractor (<class 'custom_components.xiaomi_cloud_map_extractor.camera.VacuumCamera'>) implements device_state_attributes. Please report it to the custom component author

2. Update of camera.xiaomi_cloud_map_extractor is taking over 10 seconds

3. The camera entity camera.xiaomi_cloud_map_extractor does not support requesting width and height, please open an issue with the integration author

**Comment by PiotrMachowski** [comment]
Problem should be solved in v2.1.2

**Comment by Enzokot** [comment]
@PiotrMachowski with v2.1.3 after restart my instance this warning appears one time:
`The camera entity camera.roborock_vacuum_map does not support requesting width and height, please open an issue with the integration author
`

**Comment by PiotrMachowski** [comment]
@Enzokot are you sure you have this version installed...? You can check it by looking at `manifest.json`: it should contain `pycryptodome`

**Comment by rainman369** [comment]
> @Enzokot are you sure you have this version installed...? You can check it by looking at `manifest.json`: it should contain `pycryptodome`

I am still getting the sam
![xai](https://user-images.githubusercontent.com/61566782/148049771-11083378-a8a7-4bc4-ad9c-ce15f4280ce6.png)
e errors as well after the update and I have confirmed that I have pycryptodome in my manifest.json

**Comment by rainman369** [comment]
Ultimately, the vacuum works as scheduled and the map seems to work, but it does throw the log errors regardless. 
![1](https://user-images.githubusercontent.com/61566782/148050085-041fbdef-f490-486f-8c11-dafb51bcc7f7.jpg)
![2](https://user-images.githubusercontent.com/61566782/148050087-3b5adeaf-d0c8-401d-b20c-f286f2768715.jpg)

**Comment by PiotrMachowski** [comment]
@rainman369 well, you don't get the same errors, (1) and (3) from your [earlier comment](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor/issues/168#issuecomment-997394757) are now gone. Ones you get depend on connection to your vacuum, which seems to be a bit unstable

**Comment by Enzokot** [comment]
@PiotrMachowski but `manifest.json` with old version 
https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor/blob/master/custom_components/xiaomi_cloud_map_extractor/manifest.json#L17

**Comment by rainman369** [comment]
> @rainman369 well, you don't get the same errors, (1) and (3) from your [earlier comment](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor/issues/168#issuecomment-997394757) are now gone. Ones you get depend on connection to your vacuum, which seems to be a bit unstable

You are correct, my fault :D I may try to re-do the install process at some point, but I think you're right and it just isn't very stable (which would be for a number of reasons). Thanks for your continued work on this project.

**Comment by PiotrMachowski** [comment]
@Enzokot damn, I forgot to update this value...

**Comment by Enzokot** [comment]
@PiotrMachowski I reinstall from `HACS` but after two restarts my instance this warning appears anyway

**Comment by PiotrMachowski** [comment]
@Enzokot ok, my bad, this change has somehow is missing, fix coming soon

**Comment by PiotrMachowski** [comment]
Ok, it's fixed now in v2.1.5
