### ISSUE TITLE
New installation not working: Failed to login

### ISSUE THREAD

**Issue by AxelFooley** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#645]
### Checklist

- [x] I have updated the integration to the latest version available
- [x] I have checked if the problem is already reported

### The problem

Hi, i followed the documentation to install this integration with the recommended configuration.

I am able to extract the token via the python script successfully, but once i restart HA i get these logs:

```
homeassistant    | 2025-09-03 11:44:29.473 WARNING (MainThread) [homeassistant.components.camera] Updating xiaomi_cloud_map_extractor camera took longer than the scheduled update interval 0:00:05
homeassistant    | 2025-09-03 11:44:30.600 ERROR (SyncWorker_2) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
homeassistant    | 2025-09-03 11:44:30.601 WARNING (SyncWorker_2) [custom_components.xiaomi_cloud_map_extractor.camera] Got exception while fetching the state: Unable to recover failed command
```

I looked at other issues opened but couldn't find a solution.

I'm not sure if it's related, but i have the new Xiaomi H40 maybe it's not yet supported?

### What version of an integration has described problem?

Latest

### What was the last working version of an integration?

None

### What vacuum model do you have problems with?

xiaomi.vacuum.ov51gl

### What version of Home Assistant do you use?

core-2025.7.1

### What type of installation are you running?

Home Assistant Container

### Camera's configuration

```yaml
camera:
  - platform: xiaomi_cloud_map_extractor
    host: !secret xiaomi_vacuum_host
    token: !secret xiaomi_vacuum_token
    username: !secret xiaomi_cloud_username
    password: !secret xiaomi_cloud_password
    draw: ['all']
    attributes:
      - calibration_points
```

### Errors shown in the HA logs (if applicable)

```shell

```

**Comment by tekkitlx** [comment]
I get the same. I have a xiaomi s20 but also get this error and map screen says failed to log in

**Comment by MaryanVP** [comment]
> У меня то же самое. У меня Xiaomi S20, но тоже появляется эта ошибка, и на экране карты написано, что не удалось войти в систему.

+1

**Comment by kawsoft** [comment]
Такое ощущение, что это проделки РКН. У меня тоже данная ошибка появилась после ребута. В теме ниже было написано ждите ищут проблему. Я оставил попытки пока и вот на второй день интеграция подключилась сама, думаю просто запросы пробились. И пока все работает, но думаю до следующего ребута. 
Как то так!

**Comment by xumixu** [comment]
The issue is xiaomi blocking the loging by asking a captcha which you cant open directly in the VM, and if you solve it in your computer it does nothing (it will still ask for it again).

I got tired of it. I removed it from HA and will just be using it in the app, and ofc i'm not buying any xioami smart thingies in the future. This is not Piotr fault, but he is nother victim of xioami being AHs. And the most effective way to speak to them is through our wallets and sharing the info so other do the same.

**Comment by lauramelerogarrigos** [comment]
Buenos días.
Tengo el mismo problema, ¿hay alguna solución?

**Comment by patog** [comment]
same here ... Login failed in new installation

**Comment by Aspirisha** [comment]
You can fix it. To obtain token, follow the procedure described in https://github.com/PiotrMachowski/Xiaomi-cloud-tokens-extractor/issues/43#issuecomment-1186615161, and once you have it (together with `ssecurity` and `userId`), update `config/custom_components/xiaomi_cloud_map_extractor/common/xiaomi_cloud_connector.py` and `config/custom_components/xiaomi_cloud_map_extractor/camera.py`

I confirm that it helped me resolving the issue with login - though I had the same problem initially.

**Comment by felipebraz** [comment]
+1

**Comment by LionCityGaming** [comment]
> You can fix it. To obtain token, follow the procedure described in [PiotrMachowski/Xiaomi-cloud-tokens-extractor#43 (comment)](https://github.com/PiotrMachowski/Xiaomi-cloud-tokens-extractor/issues/43#issuecomment-1186615161), and once you have it (together with `ssecurity` and `userId`), update `config/custom_components/xiaomi_cloud_map_extractor/common/xiaomi_cloud_connector.py` and `config/custom_components/xiaomi_cloud_map_extractor/camera.py`
> 
> I confirm that it helped me resolving the issue with login - though I had the same problem initially.

What exactly do I have to update in those files? I have all the necessary info, but don't know what to do with them.

**Comment by Aspirisha** [comment]
So, in file `config/custom_components/xiaomi_cloud_map_extractor/common/xiaomi_cloud_connector.py` set up `_ssecurity`, `_userId` and `_serviceToken` fields in `__init__` method of `XiaomiCloudConnector` - [here](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor/blob/master/custom_components/xiaomi_cloud_map_extractor/common/xiaomi_cloud_connector.py#L37-L51) it is in this repo.

In file `config/custom_components/xiaomi_cloud_map_extractor/camera.py` replace assignment [`self._logged_in = self._connector.login()`](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor/blob/master/custom_components/xiaomi_cloud_map_extractor/camera.py#L300) with assignment to constant `self._logged_in=True` to avoid failing login procedure and just force the hardcoded `XiaomiCloudConnector` to use hardcoded values.

**Comment by AxelFooley** [comment]
I followed the instructions, the token extractor works (but it used to work even before raising this issue so i'm not sure what's the change here).

I've also modified the map extractor custom component and now i'm getting this:

```
Logger: homeassistant.helpers.entity
Source: helpers/entity.py:963
First occurred: 11:02:10 (2 occurrences)
Last logged: 11:02:14

Update for camera.xiaomi_cloud_map_extractor fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 963, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1316, in async_device_update
    await hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 59, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/xiaomi_cloud_map_extractor/camera.py", line 291, in update
    self._handle_map_data(self._map_name)
    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "/config/custom_components/xiaomi_cloud_map_extractor/camera.py", line 362, in _handle_map_data
    map_data, map_stored = self._device.get_map(map_name, self._colors, self._drawables, self._texts,
                           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                self._sizes, self._image_config, store_map_path)
                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xiaomi_cloud_map_extractor/common/vacuum.py", line 27, in get_map
    response = self.get_raw_map_data(map_name)
  File "/config/custom_components/xiaomi_cloud_map_extractor/common/vacuum.py", line 45, in get_raw_map_data
    map_url = self.get_map_url(map_name)
  File "/config/custom_components/xiaomi_cloud_map_extractor/common/vacuum_v2.py", line 18, in get_map_url
    if api_response is None or "result" not in api_response or "url" not in api_response["result"]:
                                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable
```

**Comment by LionCityGaming** [comment]
> So, in file `config/custom_components/xiaomi_cloud_map_extractor/common/xiaomi_cloud_connector.py` set up `_ssecurity`, `_userId` and `_serviceToken` fields in `__init__` method of `XiaomiCloudConnector` - [here](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor/blob/master/custom_components/xiaomi_cloud_map_extractor/common/xiaomi_cloud_connector.py#L37-L51) it is in this repo.
> 
> In file `config/custom_components/xiaomi_cloud_map_extractor/camera.py` replace assignment [`self._logged_in = self._connector.login()`](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor/blob/master/custom_components/xiaomi_cloud_map_extractor/camera.py#L300) with assignment to constant `self._logged_in=True` to avoid failing login procedure and just force the hardcoded `XiaomiCloudConnector` to use hardcoded values.

Yeah, also didn't work for me. Displays `Failed to retrieve device`, but the Token Extractor still returns the same values as before, so not sure what's wrong there.

**Comment by Merwenus** [comment]
Is there a working fix for this? I installed the latest alpha, but can't login.

**Comment by Aspirisha** [comment]
@LionCityGaming did you check that the values you obtained are correct and if you update https://github.com/PiotrMachowski/Xiaomi-cloud-tokens-extractor with them the script outputs you token and other information about the device?

**Comment by LionCityGaming** [comment]
> @LionCityGaming did you check that the values you obtained are correct and if you update https://github.com/PiotrMachowski/Xiaomi-cloud-tokens-extractor with them the script outputs you token and other information about the device?

Yeah, I checked them thoroughly, and multiple times. And yes, the Token Extractor shows me the device. So I don't know what exactly is wrong here. 🙏

**Comment by PiotrMachowski** [comment]
I have released a new alpha version of Map Extractor - it supports Captcha, 2FA and storing session
https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor/releases/tag/v3.0.0-alpha-8

**Comment by lauramelerogarrigos** [comment]
Hi, i test the new alpha versión of Map Extractor and I no longer have the login error but receive this error:
Error de configuración, se volverá a intentar: Can't instantiate abstract class MapDataParser without an implementation for abstract methods 'parse', 'unpack_map'.
What could be the reason for this?

**Comment by PiotrMachowski** [comment]
@lauramelerogarrigos Try reinstalling it and restarting HA

**Comment by Merwenus** [comment]
> I have released a new alpha version of Map Extractor - it supports Captcha, 2FA and storing session https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor/releases/tag/v3.0.0-alpha-8

This fixed the problem, works again. Thank you

**Comment by lauramelerogarrigos** [comment]
> [@lauramelerogarrigos](https://github.com/lauramelerogarrigos) Try reinstalling it and restarting HA

I've tried that, but I'm still getting the same error. Could it be because of my Roomba model? I have the Xiaomi Vacuum X20.

**Comment by AxelFooley** [comment]
Tried as well, I can confirm that the captcha and 2FA now work within the integration.
I noticed that after extracting my token where I have to select my robot:

1. Xiaomi is not even listed
2. It selects "unsupported" automatically 

Then in then integration I have

Failed setup, will retry: Can't instantiate abstract class MapDataParser without an implementation for abstract methods 'parse', 'unpack_map'

**Comment by PiotrMachowski** [comment]
@lauramelerogarrigos @AxelFooley ok, so at this moment your models are not supported

**Comment by AxelFooley** [comment]
> @lauramelerogarrigos @AxelFooley ok, so at this moment your models are not supported 

Thanks mate. Mine is a Xiaomi H40, I'll sit back and wait, hopefully you'll manage to add support soon

**Comment by xumixu** [comment]
3.0.8 working ok with viomi v8 (asked both captcha and 2fa)

Thanks!

Also didn't even need to input the token and IP, it extracted it by itself from the cloud (even recognized that i had 2 different vacuums)

**Comment by enzomarin** [comment]
I managed to add my vacuum cleaner in version 3.0.0-alpha8, but the integrations show this error: "Configuration error, will try again: 'NoneType' object is not subscriptable."

<img width="1277" height="426" alt="Image" src="https://github.com/user-attachments/assets/b65b7d5b-d015-412f-8fe2-da671caf9998" />

**Comment by tekkitlx** [comment]
> Tried as well, I can confirm that the captcha and 2FA now work within the integration. I noticed that after extracting my token where I have to select my robot:
> 
> 1. Xiaomi is not even listed
> 2. It selects "unsupported" automatically
> 
> Then in then integration I have
> 
> Failed setup, will retry: Can't instantiate abstract class MapDataParser without an implementation for abstract methods 'parse', 'unpack_map'

Yeah exact same for my model Xiaomi S20, very excited though that the solution for captchas and 2FA is working fine!!

**Comment by felipebraz** [comment]
> I have released a new alpha version of Map Extractor - it supports Captcha, 2FA and storing session https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor/releases/tag/v3.0.0-alpha-8

This version solved the issue with 2FA and the authentication is working, now I'm having the issue with unsupported device... 😢 
I have an Xiaomi X20 Plus... I know that still unsupported, maybe in the future...
Thanks for the fix!

**Comment by graber0509** [comment]
Hello! Thank You for 2FA ant the auth fix. I have **dreame.vacuum.mc1808**. Integration also detects that I need dreame map type. This model was supported at previous versions but now I'm get an error:

```
Unexpected error fetching xiaomi_cloud_map_extractor data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 392, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 293, in _async_update_data
    return await self.update_method()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xiaomi_cloud_map_extractor/coordinator.py", line 36, in update_data
    return await self.connector.get_data()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xiaomi_cloud_map_extractor/connector/__init__.py", line 77, in get_data
    await self._get_map()
  File "/config/custom_components/xiaomi_cloud_map_extractor/connector/__init__.py", line 140, in _get_map
    await self._update()
  File "/config/custom_components/xiaomi_cloud_map_extractor/connector/__init__.py", line 108, in _update
    map_data, map_saved, map_raw_data = await self._vacuum_connector.get_map()
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xiaomi_cloud_map_extractor/connector/vacuums/base/vacuum_base.py", line 78, in get_map
    map_name = await self.get_map_name()
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xiaomi_cloud_map_extractor/connector/vacuums/vacuum_dreame.py", line 78, in get_map_name
    self._dreame_vacuum.call_action("map_view", params=[{'piid': 2, 'value': '{"frame_type":"I"}'}])
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/miio/click_common.py", line 184, in _wrap
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.13/site-packages/miio/miot_device.py", line 89, in call_action
    raise DeviceException(f"{name} is not an action (missing siid or aiid)")
miio.exceptions.DeviceException: map_view is not an action (missing siid or aiid)
```

**Comment by davemenkehorst** [comment]
Connection to vacuum failed, please check the configuration.

I have a Xiaomi 1M. It always worked before the 2FA period
It filled in the correct API key and IP address

Edit: It worked with the CN server and not the DE server

**Comment by PiotrMachowski** [comment]
@graber0509 please try this one:
https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor/releases/tag/v3.0.0-alpha-9

**Comment by LionCityGaming** [comment]
I have a Roborock S7 MaxV Ultra. It works fine with the Roborock integration. But When using the Map Extractor:

<img width="510" height="727" alt="Image" src="https://github.com/user-attachments/assets/54bee321-539a-412c-96dd-3badaf50847c" />

But it works with selecting _Unsupported_. Is that expected behaviour?

Also, the Vacuum Map Card throws up the following _Invalid Calibration_ error as well:

<img width="464" height="755" alt="Image" src="https://github.com/user-attachments/assets/91fc6149-699d-4c14-bcdf-359b221dee77" />

Any advice?

**Comment by PiotrMachowski** [comment]
If you use the Roborock integration then you shouldn't use Map Extractor.
If you want to use it because of Map Card then install and configure [this integration](https://github.com/Lash-L/RoborockCustomMap/) on top of built-in Roborock one.

**Comment by LionCityGaming** [comment]
> If you use the Roborock integration then you shouldn't use Map Extractor. If you want to use it because of Map Card then install and configure [this integration](https://github.com/Lash-L/RoborockCustomMap/) on top of built-in Roborock one.

Thank you so much for this! It works now!

**Comment by graber0509** [comment]
> [@graber0509](https://github.com/graber0509) please try this one: https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor/releases/tag/v3.0.0-alpha-9

<img width="40%" height="40%" alt="Image" src="https://github.com/user-attachments/assets/8c4f1be8-009d-4f2d-b325-1d97e3307e5c" />

Thank You very much! Everything works fine after those fixes!

**Comment by Wrzesio** [comment]
I have a roborock S5 and I'm having the same configuration problem in both Alpha 8 and 9. When I log in, I can see the roborock IP and token, but when I try to connect, I get the error: 'Connection to vacuum failed, please check the configuration.' Do you have any ideas how to fix this? Also, I don’t have a roborock account I only use the xiaomi home  app.

<img width="390" height="552" alt="Image" src="https://github.com/user-attachments/assets/ac972fd5-c1ac-41af-aac1-4e05a00a5967" />

**Comment by PiotrMachowski** [comment]
@Wrzesio is the vacuum on the same network as HA?

**Comment by Wrzesio** [comment]
@PiotrMachowski yes, but I found an issue with my router. It works now, thanks!

**Comment by pawg** [comment]
> [@lauramelerogarrigos](https://github.com/lauramelerogarrigos) [@AxelFooley](https://github.com/AxelFooley) ok, so at this moment your models are not supported

Thanks Piotr! Login is now working perfectly, but I also have a Xiaomi S20, so it isn't supported yet.

Are you planning to add the Xiaomi line of vacuums soon?

EDIT: can we help by providing any relevant data?

**Comment by AxelFooley** [comment]
I am also available to assist with integrating the H40 of you provide instructions on what to do

**Comment by flyibeat** [comment]
Chinese users are required to provide mobile verification codes instead of email verification codes, so that when I enter an email verification code during login, an error is prompted.



Unable to determine finish location after verifyEmail
Unexpected exception while attempting to Miio cloud get devices
argument should be a bytes-like object or ASCII string, not 'NoneType'

<img width="414" height="263" alt="Image" src="https://github.com/user-attachments/assets/8dfb734b-4f1b-46a4-b5e5-d42fc321d4fa" />

**Comment by PiotrMachowski** [comment]
@flyibeat I will add QR login soon, it should resolve these issues

**Comment by flyibeat** [comment]
That's great, thanks!




貊貊
***@***.***

**Comment by rshadow** [comment]
Thanks! Everything is working. There was a captcha and a 2FA with an email code.

v3.0.0-alpha-9

**Comment by LeidenSpain** [comment]
> [@graber0509](https://github.com/graber0509) please try this one: https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor/releases/tag/v3.0.0-alpha-9

I tried replacing the current folder with the beta one, but it shows me this error:

```
Este error se originó a partir de una integración personalizada.

Registrador: py.warnings
Fuente: custom_components/xiaomi_cloud_map_extractor/connector/vacuums/vacuum_dreame.py:4
integración: xiaomi_cloud_map_extractor (documentación, problemas)
Ocurrió por primera vez: 19:22:12 (1 ocurrencia)
Última vez registrado: 19:22:12

/usr/local/lib/python3.13/site-packages/miio/miot_device.py:23: FutureWarning: functools.partial will be a method descriptor in future Python versions; wrap it in enum.member() if you want to preserve the old behavior Bool = partial(_str2bool)
```

I deleted everything, started from scratch, and now it asks me for the Captcha, although it gave me an error at the end.

I'm still trying.

**Comment by PiotrMachowski** [comment]
@LeidenSpain this is just a warning and it is from external library

Can you check if [Tokens Extractor](https://github.com/PiotrMachowski/Xiaomi-cloud-tokens-extractor/) works for you when you try to log in with password (not QR code)?

**Comment by LeidenSpain** [comment]
Nothing, same error.
After entering the 2FA code, this screen appears:

<img width="379" height="226" alt="Image" src="https://github.com/user-attachments/assets/875da078-c4e9-48de-8d7e-55ce8f7714b0" />

and at the end, this message and it does not continue:

<img width="431" height="287" alt="Image" src="https://github.com/user-attachments/assets/ebb0ac2c-9390-46cf-b134-399ac913014a" />

**Comment by LeidenSpain** [comment]
> [@LeidenSpain](https://github.com/LeidenSpain) this is just a warning and it is from external library
> 
> Can you check if [Tokens Extractor](https://github.com/PiotrMachowski/Xiaomi-cloud-tokens-extractor/) works for you when you try to log in with password (not QR code)?

I have the token and I'm using it without problems with Xiaomi Home (I can control the roborock)

<img width="1015" height="157" alt="Image" src="https://github.com/user-attachments/assets/ebfab048-6a86-41e6-a400-0609f8d68928" />

**Comment by PiotrMachowski** [comment]
> I have the token and I'm using it without problems with Xiaomi Home (I can control the roborock)
> 

It's not about the token, it's about checking if logging in works. But now I see that you have a different problem. Most probably you have selected a wrong server.

**Comment by LeidenSpain** [comment]
> > I have the token and I'm using it without problems with Xiaomi Home (I can control the roborock)
> 
> It's not about the token, it's about checking if logging in works. But now I see that you have a different problem. Most probably you have selected a wrong server.

I swear I used DE, but I'm trying again.

**Comment by LeidenSpain** [comment]
> > I have the token and I'm using it without problems with Xiaomi Home (I can control the roborock)
> 
> It's not about the token, it's about checking if logging in works. But now I see that you have a different problem. Most probably you have selected a wrong server.

Sorry, you were right: I just checked the app and I have the CN server.

Sorry for the inconvenience.

**Comment by LeidenSpain** [comment]
Well, a different problem.
I uninstalled the integration to check something, and now I haven't received the verification email from Xiaomi.

I'll try again tomorrow, because I've already requested it like four times today and I haven't received the email.

**Comment by PiotrMachowski** [comment]
I have added QR code authentication
https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor/releases/tag/v3.0.0-alpha-10

@flyibeat it might solve your issue

**Comment by flyibeat** [comment]
> I have added QR code authentication https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor/releases/tag/v3.0.0-alpha-10
> 
> [@flyibeat](https://github.com/flyibeat) it might solve your issue

yeah，It worked. thank you

**Comment by LeidenSpain** [comment]
> Well, a different problem. I uninstalled the integration to check something, and now I haven't received the verification email from Xiaomi.
> 
> I'll try again tomorrow, because I've already requested it like four times today and I haven't received the email.

The problem was finally (and I'm leaving a note in case it happens to someone else) that Xiaomi has a limit of 3 or 5 daily verifications (depending on whether it's a Chinese server or not)

**Comment by sven2105** [comment]
@PiotrMachowski when will you merge the fix into master branch?

**Comment by PiotrMachowski** [comment]
@sven2105 I'm not sure, it's hard to tell

**Comment by wolfmaster8** [comment]
Hi @PiotrMachowski, I just tried the latest alpha with my X20 Max (d109gl) but I see this error after configuring the integration (successful auth and vacuum config):

<img width="779" height="253" alt="Image" src="https://github.com/user-attachments/assets/8c1e3a95-eb99-4d1e-8aa6-c66d883a83b6" />

These logs keeps repeating until I disable the integration
<img width="769" height="136" alt="Image" src="https://github.com/user-attachments/assets/77f5ec63-4dbf-49fe-8b5a-0f44c8e4502f" />

**Comment by PiotrMachowski** [comment]
@wolfmaster8 your vacuum doesn't seem to be supported. At this moment the only thing you can do is to remove the integration, add it again, switch vacuum platform to unsupported and send me diagnostic data

**Comment by MysteriousWolf** [comment]
It may have something to do with the newer mi vacuums that are actually produced in house (I have H40EU). I had a similar issue to the one reported by @wolfmaster8, so this log might help.

[config_entry-xiaomi_cloud_map_extractor-01KB8F2Z6WDYEZN7247B3FX2PF.json](https://github.com/user-attachments/files/23835361/config_entry-xiaomi_cloud_map_extractor-01KB8F2Z6WDYEZN7247B3FX2PF.json)

**Comment by dCypherNx** [comment]
this is my d109gl diagnostics
<details>
  <summary>Logs</summary>

```
2025-12-01 11:24:28.162 DEBUG (MainThread) [custom_components.xiaomi_cloud_map_extractor.connector.xiaomi_cloud.connector] Restoring connector config...
2025-12-01 11:24:28.169 DEBUG (MainThread) [custom_components.xiaomi_cloud_map_extractor.connector] Downloading new map.
2025-12-01 11:24:28.169 DEBUG (MainThread) [custom_components.xiaomi_cloud_map_extractor.connector] Restoring connector configuration...
2025-12-01 11:24:28.170 DEBUG (MainThread) [custom_components.xiaomi_cloud_map_extractor.connector] Initializing...
2025-12-01 11:24:28.170 DEBUG (MainThread) [custom_components.xiaomi_cloud_map_extractor.connector] Retrieving device info, server: us
2025-12-01 11:24:28.171 DEBUG (MainThread) [custom_components.xiaomi_cloud_map_extractor.connector.xiaomi_cloud.connector] Request URL: https://us.api.io.mi.com/app/v2/homeroom/gethome
2025-12-01 11:24:29.355 DEBUG (MainThread) [custom_components.xiaomi_cloud_map_extractor.connector.xiaomi_cloud.connector] API response: Ij6uPe5iVQkZUPeD2b7QiMxn8YboXwreFhlSqOA6swDYsWEP/1vbHoBVxKnNYGpB2JoX9Oqv4semVrOwtCK3UcZ84z8GAKJDLO3u5feBXiq/BC58zm/G+i61r4R+FGYhGxRs4b5af5mLWkJOQR/FaQc6AABQnTkiin5nyiV/Or+fWeU4cjrJeepBPlwGD2PhjcYx1/+AnQscE+kefVHt+Y3Z3NW65bbfXhSxXkH2I4DRF3H4qN9YblBkRoIl54FWhyOH+pgHbT3+AgpLHntqSE3prz15DFpm7En8FOPcXcu2E0fuW3AY72qtZo1rlzucRjmeUmiRi1BDZ9TvhlHJbi8OiaNJrj2pSY9FgEOO3egMRaal9DxHLSWykCWMAPNtJ4JdEdEX1l/lMzgQGbx9bOrSJI8moyd9XQr21uu1H3E3/wSoVxH++Md1i7hM+VtuKi2M1ayyFIW2FF1I6hbx8ihioR6jx+vaC6f06+xxyznkmiwNz823grkkXEk/H7LHX7Tn5MsBJSQxigBbp2jV9k0JbQI+oEic0uSOoq3UFwAQSxikZoSSYaGpGat8cCgiz2Jt/2o5lp/HPQcB0kvjSPbvuzgFxPrbOftgV4jJdhqBW9mjiMcv+NHWD963FgCJfXslxTq7HlCiXCccPpJjt5tp72ZDjnuePinCtmNsSGkBzWux0IoEJ1yQwNgTic/SMasiL5gC5nrGBVyFMHQWq5ql/baZ2yQmmlrK1Wzawmre2pD8Jm9O6OR4gICTjZ6voWvNqz2fmFZusTGUvUYmOvID0F0a25L53y91JA59IkJ6lSlbKBy4h3JqhgpOiC5fdklb9aGXia7E4tUUhtkZT53U6gqvFz65XAoLpT4mFKgezKllW7wGTxcl+O51mqjgNheAB+tPlvEyYtWlCHbFWTN9IE3GQuwI2uqyfSBUlr45XZ7cNcngWo75P80ECkl9yGCNfCcsw1XQRXhNTOzHpBFF+KjiD40gqX8mpI7Ah+3+nrsOukCV+cWeZtNOdLsddKC5sKcbGxvZJtEgimE=
2025-12-01 11:24:29.356 DEBUG (MainThread) [custom_components.xiaomi_cloud_map_extractor.connector.xiaomi_cloud.connector] Request URL: https://us.api.io.mi.com/app/v2/home/home_device_list
2025-12-01 11:24:29.765 DEBUG (MainThread) [custom_components.xiaomi_cloud_map_extractor.connector.xiaomi_cloud.connector] API response: llYvWpa55aCtCNNuHAgWuLyOb/UyKB0U8lfVOamodYXEgtKQrAZTNewPHhPMtSYsFHleVws9oWsjdjQrfC3ZAS8D9L2JwByCwI3KGtNni2B4zA6tIJQu+S0gezE9roJ9NMBcGYve6n8hS2w+lmKD8Me3jqiWh5uQ+4on8HE0ErpxgnjxhRzfbXonY8nZPTcs5DbRvjBLSueefo2ZzkPayENqGsgsGUISc/BwUmJkeM4jgg8MgxsgIpcnTcSb6sWCbiaKaa/wEIXDKO5WOMqING51/1fvGkq+FLAO6XOfgB9cqKgiUtpDBtrfm+K9BTO6cygSu4+nzadouoXoBELkkOX7aWElxcBnlM3VYwjP2Tdq7SzLSUGRkN06eIZ3XTX2PDASkx3im/DtZoYRsh2BW3rXnoz74nGIU3a7JpaV/gAnzhd2acIZLUtonp+k49k4oika26IM5kLi3XzMTAwHTHCtWQp4/vZmtrjjAYJ6OzO7f2NeIQYs/KTSsWt4ZZNOH8sO8wHrZjVagaiyERvZoLalLLjNxZvVeJ94Ia6+b1qz4FA/OUQP6UG0Y0EPZIzKnm1THTOz9vis4ycVMjIQcPUvuKBoBViPoscArqPqYSfVNJPPN1getc9FNRuDbs9gEuSLsu9bB/RF1C9lqY4VWCdXRjTCmX0yZUwswP3jm3u28AW0z8DONyyiORfIwQcMU7TyBXerJfD8JD3bFa/H9JYWpXIv0zoT+G4giQnN6ipLqZOo94wvrHGUPXlEfTgZb5i3B9jKALV6NV9V14H6Aau0S3pOqmdP2AztnO0+HKSRwnwtdVDkB9he7/5mjOr16GfAzaXh1mQ5hh42HTfT+5WHjp0gg0EIsLYXyxDk8lP2CbXyrx19xGsH9vPk352ap1SclMtP1Gv2+t+HiqYQT4PofgazTiAz4NmIquJuDl405Oiib1jRaaZ0T2gJk4TjV9WW8eE94FUkUHw3iRAg1DAFon2Z19mDGMC6UxE3D9EGcUbAp7bErHogNMPRL8R4RnfwMCBG9qUI45VsOYSPeqUTviSnGsadOPmGmwsKG401VWBMbJuIrFXcbFAs2PQFy/2pt/4VnqauglhnTpy3hTsNta7qRIRt+X6R6q6X98PGcrtGjSumrF/i4yTmwOK/6nAAq0ihD82KFGuQyek0LpR6yFD7UWg/xH/RrG6FKXoBJIUxFukEZpoBTwIXDXL1R5tdMeeZwefPx45jT4D/C6SHD44cIhCz7N1ERYaDuw3S38iBWGtZ9FeNpYHF4DTpAZqqIIUc2MTiDGCRwd+520EL07Tb9zYrXKTjGyiTynRwxQUf8yMm6I3+QuQI5EWf8nuysyjJnQoFhIdGbXLgDWfWt8P+W0dDLpYVsCeFQ765QqYBWWPA35vyMrjkOBUl3SzJguUfG7KAFSnEG6YNaVLmuo7zraI6Ge61wQ8aLjrCLxTtNGRHzRczE4bjMXjmp/kLHMEnyD215wCaVtbSwxgk4KmSt6mVugIqMy5sLxyUSOBaAMGlsEc/3WDhNdCDwNOyC3hYo5JjI16TDqSS+1SvP+d2PDkZ+2TAV4dRlQS4Yzjrz+ZCOuXmJ7rYugtHQ1giBFh8HVr4BXxUG/uxd6Dr+3K9DiC6Qkd0Z05nZyBRRo1lNqqfWUNWxhozNZzOvUhHgLUALvZQimIxWM8+K0yvJ58gVrF2vyoOwv4//Walbcjw5TUiwx4DyEsGEndlx1bxTSnCDYcl5kFEV1M9KLmwx0lULzW3DEtz0KpcVslhP3qDTXgsw5b/5IWGfb5ORE007OIsYNbMsDSQFhb/FkwAUi53dTHoanaiQK0oKkKBCCbonze9+bFijvZ4+8YpkmfTp0uEJYPYi/IgYL4GTS6+Lcks4NS0X9Z8myYjW/le5DEdRjbBVeQnsNA/M7+aNPdnwmyJACgzA5cpXz9IxEyeT6ZeIyqU3HCAHYgGCheFZjMKScQOIbH85vo1R+4K3/65e72wYtmk6D4SBKKRr0NRJlXfhWvlNHbfiU3u55xvNymkY73YLyK0
2025-12-01 11:24:29.765 DEBUG (MainThread) [custom_components.xiaomi_cloud_map_extractor.connector] Retrieved device model: xiaomi.vacuum.d109gl
2025-12-01 11:24:29.765 DEBUG (MainThread) [custom_components.xiaomi_cloud_map_extractor.connector] Created device, used api: UNSUPPORTED
2025-12-01 11:24:29.765 DEBUG (MainThread) [custom_components.xiaomi_cloud_map_extractor.connector] Initialized.
2025-12-01 11:24:29.765 DEBUG (MainThread) [custom_components.xiaomi_cloud_map_extractor.connector] Downloading map...
2025-12-01 11:24:29.765 DEBUG (MainThread) [custom_components.xiaomi_cloud_map_extractor.connector.vacuums.base.vacuum_base] Getting map name...
2025-12-01 11:24:29.765 DEBUG (MainThread) [custom_components.xiaomi_cloud_map_extractor.connector.vacuums.base.vacuum_base] Got map name: "0".
2025-12-01 11:24:29.765 DEBUG (MainThread) [custom_components.xiaomi_cloud_map_extractor.connector.vacuums.base.vacuum_base] Downloading map...
2025-12-01 11:24:29.766 DEBUG (MainThread) [custom_components.xiaomi_cloud_map_extractor.connector.xiaomi_cloud.connector] Request URL: https://us.api.io.mi.com/app/v2/home/get_interim_file_url
2025-12-01 11:24:30.210 DEBUG (MainThread) [custom_components.xiaomi_cloud_map_extractor.connector.xiaomi_cloud.connector] API response: TYTi5sCFyrh5yv2Q3sr/O4RcD0Jh0wKpkMg2hBgjwwwBewaDf7INiu4M2nIXghlPTfprD+AinLmYSybE
2025-12-01 11:24:30.210 DEBUG (MainThread) [custom_components.xiaomi_cloud_map_extractor.connector.xiaomi_cloud.connector] Request URL: https://us.api.io.mi.com/app/v2/home/get_interim_file_url_pro
2025-12-01 11:24:30.588 DEBUG (MainThread) [custom_components.xiaomi_cloud_map_extractor.connector.xiaomi_cloud.connector] API response: h55Zhl/yQTzILgiYRCzmwnfzQhTy8i6GLs7QJlL/tfk2+lmnAUk7GPr8ScyagXsV7r1qcwmt8DiKfi2mUT217dBDgBn516vAkEASthus17yQWJZlSiumjyX9FU3Xe/g9vP8xuR7L6uGAfQrZLyTundZ8vIZSit+RHNimbOY3sHTYaBESFzGGjp/cbxmvVAWeer07mx0hmv9u6yziA0tCFu727DdXuA812QqksVyCZEbpfMwPFJcbQk1sy6jenpWBzFd/uCoDqkUQElPZBfdfbZEfsK89ekaW2xmvgNbGDzUkClvGn4zFmvGUNKobxrCpOb4oOzLDjBAyv98EBvW/xeqgI9OZEDj8rTdqXk5x2/TNRjEacKCbv/IwuY865GTTvgOOp4OF
2025-12-01 11:24:30.589 DEBUG (MainThread) [custom_components.xiaomi_cloud_map_extractor.connector.xiaomi_cloud.connector] Downloading raw map from "https://awsusor1.fds.api.xiaomi.com/xiaomi-d109gl/6341124368/1154592068/0?Expires=1764600870000&GalaxyAccessKeyId=AKAB32SK5SPXABOK3E&Signature=Fn4z0+yljjYwkxX220Q0+YpPhPY="...
2025-12-01 11:24:32.038 DEBUG (MainThread) [custom_components.xiaomi_cloud_map_extractor.connector.xiaomi_cloud.connector] Downloaded raw map, status: (200).
2025-12-01 11:24:32.038 DEBUG (MainThread) [custom_components.xiaomi_cloud_map_extractor.connector.xiaomi_cloud.connector] Downloaded raw map (11863).
2025-12-01 11:24:32.039 DEBUG (MainThread) [custom_components.xiaomi_cloud_map_extractor.connector.vacuums.base.vacuum_base] Downloaded raw map: "11863".
2025-12-01 11:24:32.039 DEBUG (MainThread) [custom_components.xiaomi_cloud_map_extractor.connector.vacuums.base.vacuum_base] Parsing map...
2025-12-01 11:24:32.043 DEBUG (MainThread) [custom_components.xiaomi_cloud_map_extractor.connector.vacuums.base.vacuum_base] Parsed map: (0 x 0)
2025-12-01 11:24:32.044 DEBUG (MainThread) [custom_components.xiaomi_cloud_map_extractor.connector] Downloaded map.
2025-12-01 11:24:32.047 DEBUG (MainThread) [custom_components.xiaomi_cloud_map_extractor.coordinator] Finished fetching xiaomi_cloud_map_extractor data in 3.878 seconds (success: True)
2025-12-01 11:24:32.047 INFO (MainThread) [homeassistant.components.camera] Setting up xiaomi_cloud_map_extractor.camera
2025-12-01 11:24:32.048 INFO (MainThread) [homeassistant.components.image] Setting up xiaomi_cloud_map_extractor.image
2025-12-01 11:24:32.048 INFO (MainThread) [homeassistant.components.sensor] Setting up xiaomi_cloud_map_extractor.sensor
2025-12-01 11:24:32.050 INFO (MainThread) [homeassistant.components.binary_sensor] Setting up xiaomi_cloud_map_extractor.binary_sensor
2025-12-01 11:24:32.050 INFO (MainThread) [homeassistant.components.button] Setting up xiaomi_cloud_map_extractor.button
2025-12-01 11:24:32.051 INFO (MainThread) [homeassistant.components.switch] Setting up xiaomi_cloud_map_extractor.switch

```


</details>

**Comment by PiotrMachowski** [comment]
@dCypherNx these are logs, not diagnostics

**Comment by dCypherNx** [comment]
Sorry, I misunderstood earlier and sent the wrong data. Here are the proper diagnostics.

[config_entry-xiaomi_cloud_map_extractor-01KBD47WYV2S98CYKRVHJM5A2H.json](https://github.com/user-attachments/files/23863369/config_entry-xiaomi_cloud_map_extractor-01KBD47WYV2S98CYKRVHJM5A2H.json)

**Comment by osnwt** [comment]
JFYI:

Tried to install `v3.0.0-alpha-21` for my **Roborock S7 Pro Ultra**, also was unable to login after QR auth: timeout and unknown error. According to logs it tried to go to `us.api.io.mi.com` (silently blocked from EU IPs instead of reject/fail). The same was with both UI configuration as well as with YAML configuration with my `country: xx` set (not to `us`).

After I hardcoded `server` in `return "https://" + ("" if server == SERVER_CN else (server + ".")) + "api.io.mi.com/app"`, the setup wizard went ahead and successfully finished (showing me the same device in all existing regions).

Didn't look further why it tried US (perhaps, it looks into all severs to present all available devices later). But a sudden timeout can break the setup process and has to be handled. In modern "Internet" with separated regions and a lot of IP blocks due to "our safety" or politics, it now creates a problem.

**Comment by gmmanonymus111** [comment]
Hello! I'm also facing an issue with a (currently) unsupported device, `ov31gl` AKA `Xiaomi Robot Vacuum 5` EU version. Here's the diagnostics in case it might help:

[config_entry-xiaomi_cloud_map_extractor-01KFRH4HV15TZ69WFP9JFE5F56.json](https://github.com/user-attachments/files/24838954/config_entry-xiaomi_cloud_map_extractor-01KFRH4HV15TZ69WFP9JFE5F56.json)

As a feedback:
With version `v3.0.0-alpha-21` I successfully logged in with credentials (had to wait **several minutes** for the verification email from Xiaomi...). I first used the `Ijai` option, as it was marked with an `*`, but that gave me an error similar to @wolfmaster8.

**Comment by MysteriousWolf** [comment]
> JFYI:
> 
> Tried to install `v3.0.0-alpha-21` for my **Roborock S7 Pro Ultra**, also was unable to login after QR auth: timeout and unknown error. According to logs it tried to go to `us.api.io.mi.com` (silently blocked from EU IPs instead of reject/fail). The same was with both UI configuration as well as with YAML configuration with my `country: xx` set (not to `us`).
> 
> After I hardcoded `server` in `return "https://" + ("" if server == SERVER_CN else (server + ".")) + "api.io.mi.com/app"`, the setup wizard went ahead and successfully finished (showing me the same device in all existing regions).
> 
> Didn't look further why it tried US (perhaps, it looks into all severs to present all available devices later). But a sudden timeout can break the setup process and has to be handled. In modern "Internet" with separated regions and a lot of IP blocks due to "our safety" or politics, it now creates a problem.

I don't think this is related to this specific issue discussed here

**Comment by waxweazle2001** [comment]
I also want to use these, but i got a failure that it can't login. I run the token extractor and put the values in the configuration.yaml and this works, but i don't find anything as Menthioned [https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor/issues/645#issuecomment-3325731418](url) here, how i get the Values for ssecurity and userId. I found a something in the net but don't Understand how to do it to get the Info about there values or especially what I should put where in the .py because the Naming is other than in the Configuration.yaml part.
Could anyone help me to get this to work?

**Comment by PiotrMachowski** [comment]
@waxweazle2001 Install the latest alpha version, don't modify anything

**Comment by waxweazle2001** [comment]
Now I have reinstalled the Xiaomi MI Cloud Map Extractor via HACS and imported the Blueprint. But I get an Error 

`Logger: custom_components.xiaomi_cloud_map_extractor.camera
Quelle: custom_components/xiaomi_cloud_map_extractor/camera.py:311
Integration: xiaomi_cloud_map_extractor ([Dokumentation](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor), [Probleme](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor/issues))
Erstmals aufgetreten: 13:05:51 (1 Vorkommnis)
Zuletzt protokolliert: 13:05:51
Unable to log in, check credentials`

In the configuration.yaml I entered the IP from the vacuum, the exported Token via the Token Extractor as the Country, the Username from the Xiaomi Cloud and the Passwort from the xiaomi cloud.
But where is the failure, when i don't should do any modifications as you said?

Also I get this Failure:

`Logger: miio.miioprotocol
Quelle: components/xiaomi_miio/__init__.py:257
Erstmals aufgetreten: 13:06:44 (1 Vorkommnis)
Zuletzt protokolliert: 13:06:44
Got error when receiving: timed out`

**Comment by PiotrMachowski** [comment]
@waxweazle2001 install the latest alpha, do not use the blueprint with it

**Comment by waxweazle2001** [comment]
Ok is done, but now i get the two other errors:

```
Logger: homeassistant.config_entries
Quelle: config_entries.py:795
Erstmals aufgetreten: 11:49:51 (1 Vorkommnis)
Zuletzt protokolliert: 11:49:51

Config entry 'Xiaomi Cloud Map Extractor' for xiaomi_cloud_map_extractor integration could not authenticate: None
```

And

```
Dieser Fehler stammt von einer benutzerdefinierten Integration

Logger: custom_components.xiaomi_cloud_map_extractor.legacy
Quelle: custom_components/xiaomi_cloud_map_extractor/legacy.py:403
Integration: xiaomi_cloud_map_extractor (Dokumentation, Probleme)
Erstmals aufgetreten: 11:49:51 (1 Vorkommnis)
Zuletzt protokolliert: 11:49:51

Failed to connect to Xiaomi Cloud
Traceback (most recent call last):
  File "/config/custom_components/xiaomi_cloud_map_extractor/legacy.py", line 403, in create_config_entry_data_from_yaml
    await connector.login_with_credentials(import_info[CONF_USERNAME], import_info[CONF_PASSWORD])
  File "/config/custom_components/xiaomi_cloud_map_extractor/connector/xiaomi_cloud/connector.py", line 169, in login_with_credentials
    location = await self._login_with_credentials_step_2(sign)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xiaomi_cloud_map_extractor/connector/xiaomi_cloud/connector.py", line 247, in _login_with_credentials_step_2
    raise CaptchaRequiredException(captcha_url, captcha_data)
custom_components.xiaomi_cloud_map_extractor.connector.utils.exceptions.CaptchaRequiredException: ('https://account.xiaomi.com/pass/getCode?icodeType=login&0.5136583740104059',(Code from my Token I think, because of this deleted)
```

What to do now?

**Comment by PiotrMachowski** [comment]
Try to log in using QR code
