### ISSUE TITLE
[v3 Alpha 17] Two vacuums causes incorrect entities

### ISSUE THREAD

**Issue by jeremysherriff** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#674]
### Checklist

- [x] I have updated the integration to the latest version available
- [x] I have checked if the problem is already reported

### The problem

I am aware this is Alpha, but as I do not know the cause I assume this is a problem that the Dev cannot recreate themselves.

I have logged in successfully and set colour options for one vacuum with no issues. I see around 26 entities related to that vacuum.

When adding an additional vacuum, many of the entities move to the 2nd vacuum and the first vacuum then shows only 5 entities.  

I have disabled the 2nd vacuum now so that things are stable, but you can still see the difference in entity counts here:

<img width="1153" height="544" alt="Image" src="https://github.com/user-attachments/assets/0444eb74-8261-4fc7-b34d-f667348135bc" />

### What version of an integration has described problem?

3.0.0-alpha-17

### What vacuum model do you have problems with?

viaomi.v8

### What version of Home Assistant do you use?

2025.10.4

### What type of installation are you running?

Home Assistant OS

### Camera's configuration

```yaml
Set up via GUI
```

### Errors shown in the HA logs (if applicable)

```shell
No errors
```

### Additional information

Please let me know if there are additional logs or diagnostic output that would be useful, or if this is currently expected with v3 alpha.

**Comment by PiotrMachowski** [comment]
Should be fixed in the latest alpha. It's advised to remove both vacuums before updating (just Map Extractor)

**Comment by jeremysherriff** [comment]
Yes, seems to work nicely.  I had to recreate the devices as there was lots of duplicate entities after my messing around, but that was now easy by uncommenting the YAML configuration and allowing the import to run 👍 Nice work!

**Comment by PiotrMachowski** [comment]
> that was now easy by uncommenting the YAML configuration and allowing the import to run

That's great 👍 I was afraid if migration will work for everyone. Was reauthentication necessary?

**Comment by jeremysherriff** [comment]
Yes, and with two entities it was a bit messy because the first re-auth
seemed to clear the message but did not fix the 2nd device.
I suspect if I had commented out the YAML and restarted it might have
resolved the 2nd device as well.

**Comment by PiotrMachowski** [comment]
> I suspect if I had commented out the YAML and restarted it might have resolved the 2nd device as well.

Unfortunately no, it wouldn't. At this moment every entry has its own authentication. I might merge it, but it's not top priority, at least at this moment.

**Comment by jeremysherriff** [comment]
I have viomi (v8) vacuums, can I help with code to fetch the image updates only when vacuuming?
Does this info help? https://gist.github.com/jeremysherriff/786457fd0bdbadf0a43d564889c17900

**Comment by PiotrMachowski** [comment]
It might, I'd have to check out how to get current vacuum status from Viomi vacuums.
